---
sudo: required

env:
  - distro: debian
    tag: buster
  - distro: debian
    tag: stretch

services:
  - docker

before_install:
  - 'sudo docker pull pvelati/docker-${distro}-base:${tag}'

script:
  - container_id=$(mktemp)
  - 'sudo docker run --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible/roles/test_role:ro pvelati/docker-${distro}-base:${tag} > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" pip install -r /etc/ansible/roles/test_role/requirements.txt'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/test_role/test/test.yaml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/test_role/test/test.yaml'
  - >
    sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/roles/test_role/test/test.yaml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
  - 'sudo docker exec "$(cat ${container_id})" curl http://localhost:3142'
  - 'sudo docker rm -f "$(cat ${container_id})"' 
...
